#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

## GLOBAL SETTINGS

## SPACE SETTINGS

## WINDOWS SETTINGS
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   1
yabai -m config window_shadow                float

## LAYOUT SETTINGS
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config layout                       float
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

## MOUSE SETTINGS
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# apps to not manage (ignore)
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off

echo "yabai configuration loaded.."